# example-node1-bmh-secret & assisted-deployment-pull-secret need to be created under same namespace demo-ztp-gitops
---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: "sno-gitops"
  namespace: "sno-gitops"
spec:
  baseDomain: "ocp.lsh"
  pullSecretRef:
    name: "demo-ztp-gitops-pull-secret"
  clusterImageSetNameRef: "img4.18.9-x86-64-appsub"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDX0RUJj0jroMQyUWpn5qJGHGFqNwGfSvETccfmZVN6L/FtKS0FwKtyhL+G9c+xBO2DM38qSLRDzL5/ZMd/D9N+W3NvSI0T0GMJc1RXBf1gKH3kCpVyaeujyGBbrnAL3YpDjoycWRjdVnSuXUP2exkmreZyaCLuYcnTbmgx+6GUzHsVozqQpzcteBo/e9IEVe8NhEHmoO2Ghv/xBHD/olk/wJ3hiNqltNl9uskSnlHxK28CfgeF8ExMnLnIDK9PwfxWhORTO3TaMGaCUAJjYorpgxEbpkZ1gm1o2w7rvoylgDu3XQj9CUUFlC+ouZG5DmbFKvy0auZzgMv0SKz582R64rLh0wy95XqgiRDlUH6OJc5koV1birsrqut/sRshqzVbnfZ7Ok7v0890wXIAa56OF8laliOZJEFpDKpJ2Mq1EHe8RYeDXZUq6i/aJYnAft3JqWbwZxPJaX8bT+jErQjENJWQ4OpYWtzJxLVbUWvglHFv/Xwu9TvwJSi8fQ6leA8="
  clusters:
  - clusterName: "sno-gitops"
    networkType: "OVNKubernetes"
    # installConfigOverrides is a generic way of passing install-config
    # parameters through the siteConfig.  The 'capabilities' field configures
    # the composable openshift feature.  In this 'capabilities' setting, we
    # remove all the optional set of components.
    # Notes:
    # - OperatorLifecycleManager is needed for 4.15 and later
    # - NodeTuning is needed for 4.13 and later, not for 4.12 and earlier
    # - Ingress is needed for 4.16 and later
    installConfigOverrides: |
      {
        "capabilities": {
          "baselineCapabilitySet": "None",
          "additionalEnabledCapabilities": [
            "NodeTuning",
            "OperatorLifecycleManager",
            "marketplace",
            "Ingress"
          ]
        }
      }
    # It is strongly recommended to include crun manifests as part of the additional install-time manifests for 4.13+.
    # The crun manifests can be obtained from source-crs/optional-extra-manifest/ and added to the git repo ie.sno-extra-manifest.
    # extraManifestPath: sno-extra-manifest
    clusterLabels:
      demo: gitops
      cluster.open-cluster-management.io/clusterset: demo-ztp-gitops
      sites : "sno-gitops"
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 192.168.100.0/24
    serviceNetwork:
      - 172.30.0.0/16
    #additionalNTPSources:
    #  - 2.rhel.pool.ntp.org
    # Initiates the cluster for workload partitioning. Setting specific reserved/isolated CPUSets is done via PolicyTemplate
    # please see Workload Partitioning Feature for a complete guide.
    #cpuPartitioningMode: AllNodes
    # Optionally; This can be used to override the KlusterletAddonConfig that is created for this cluster:
    crTemplates:
      KlusterletAddonConfig: "KlusterletAddonConfigOverride.yaml"
    nodes:
      - hostName: "sno-2.ocp.lsh"
        role: "master"
        # Optionally; This can be used to configure desired BIOS setting on a host:
        #biosConfigRef:
        #  filePath: "example-hw.profile"
        bmcAddress: "redfish-virtualmedia+http://bmc.sno-gitops.ocp.lsh:8000/redfish/v1/Systems/407a5c3c-8d97-4cdf-8aa5-ec25fdec1e3f"
        bmcCredentialsName: 
          name: "demo-ztp-gitops-bmc-secret-1"
        bootMACAddress: "52:54:00:51:ca:80"
        # Use UEFISecureBoot to enable secure boot
        bootMode: "legacy"
        #rootDeviceHints:
        #  deviceName: "/dev/disk/by-path/pci-0000:01:00.0-scsi-0:2:0:0"
        # disk partition at `/var/lib/containers` with ignitionConfigOverride. Some values must be updated. See DiskPartitionContainer.md for more details
        #ignitionConfigOverride: |
        #  {
        #    "ignition": {
        #      "version": "3.2.0"
        #    },
        #    "storage": {
        #      "disks": [
        #        {
        #          "device": "/dev/disk/by-id/wwn-0x6b07b250ebb9d0002a33509f24af1f62",
        #          "partitions": [
        #            {
        #              "label": "var-lib-containers",
        #              "sizeMiB": 0,
        #              "startMiB": 250000
        #            }
        #          ],
        #          "wipeTable": false
        #        }
        #      ],
        #      "filesystems": [
        #        {
        #          "device": "/dev/disk/by-partlabel/var-lib-containers",
        #          "format": "xfs",
        #          "mountOptions": [
        #            "defaults",
        #            "prjquota"
        #          ],
        #          "path": "/var/lib/containers",
        #          "wipeFilesystem": true
        #        }
        #      ]
        #    },
        #    "systemd": {
        #      "units": [
        #        {
        #          "contents": "# Generated by Butane\n[Unit]\nRequires=systemd-fsck@dev-disk-by\\x2dpartlabel-var\\x2dlib\\x2dcontainers.service\nAfter=systemd-fsck@dev-disk-by\\x2dpartlabel-var\\x2dlib\\x2dcontainers.service\n\n[Mount]\nWhere=/var/lib/containers\nWhat=/dev/disk/by-partlabel/var-lib-containers\nType=xfs\nOptions=defaults,prjquota\n\n[Install]\nRequiredBy=local-fs.target",
        #          "enabled": true,
        #          "name": "var-lib-containers.mount"
        #        }
        #      ]
        #    }
        #  }
        nodeNetwork:
          interfaces:
            - name: eth0
              macAddress: "52:54:00:51:ca:80"
          config:
            interfaces:
              - name: eth0
                type: ethernet
                state: up
                ipv4:
                  enabled: true
                  address:
                    - ip: 192.168.100.3
                      prefix-length: 24
                  dhcp: false
            dns-resolver:
              config:
                search:
                - example.com
                server:
                - 8.8.8.8
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-address: 192.168.100.1
                next-hop-interface: eth0
                table-id: 254
